version: 0.2
phases:
    install:
        commands:
            # Yarn installation
            - npm install
    pre_build:
        commands:
            # Run Automated Tests
            - npm test
    build:
        commands:
            # Build Application
            - npm run build

artifacts:
    files:
        - build/**/*
    discard-paths: yes