version: 0.2
phases:
    install:
        commands:
            # Yarn installation
            - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            - sudo apt-get -y update
            - apt-get install -y yarn
            - yarn -v
            # Installing dependencies
            - yarn install
    pre_build:
        commands:
            # Run Automated Tests
            - yarn test
    build:
        commands:
            # Build Application
            - yarn build

artifacts:
    files:
        - build/**/*
    discard-paths: yes