version: 0.2
phases:
    install:
        commands:
            # Yarn installation
            - node -v
            - npm -v
            - npm install
    pre_build:
        commands:
            # Run Automated Tests
            - npm test
    build:
        commands:
            # Build Application
            - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'build*'